server:
  port: 8888
spring:
  application:
    name: config-center
  datasource:
    url: jdbc:mysql://106.12.97.129:3306/config?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: qwe12356
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: jdbc
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT `p_key`, `p_value` FROM property a, project b, env c, label d where a.project_id=b.id and a.env_id=c.id and a.label_id=d.id and b.name=? and c.name=? and d.name=?
    bus:
      refresh:
        enabled: true
      trace:
        enabled: true
  swagger:
    enabled: true
config:
  repository: db
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
management:
  endpoint:
    bus-refresh:
      enabled: true
    bus-env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: bus-refresh,bus-env

eureka:
  instance:
    prefer-ip-address: true
    app-group-name: micro-springcloud-angular
    hostname: ${spring.cloud.client.hostname}
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8000}/eureka/