server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/letmegogoing_admin/cloud-config-repo
          username: hyx199170@gmail.com
          password: qwe12356
  application:
    name: config-server

eureka:
  instance:
    prefer-ip-address: true
    app-group-name: micro-springcloud-angular
    hostname: ${spring.cloud.client.hostname}
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8000}/eureka/