package com.cloud.configservice.model;

import java.io.Serializable;

public class EncryptKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encrypt_key.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encrypt_key.e_key
     *
     * @mbg.generated
     */
    private String eKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table encrypt_key
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encrypt_key.id
     *
     * @return the value of encrypt_key.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encrypt_key.id
     *
     * @param id the value for encrypt_key.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encrypt_key.e_key
     *
     * @return the value of encrypt_key.e_key
     *
     * @mbg.generated
     */
    public String geteKey() {
        return eKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encrypt_key.e_key
     *
     * @param eKey the value for encrypt_key.e_key
     *
     * @mbg.generated
     */
    public void seteKey(String eKey) {
        this.eKey = eKey == null ? null : eKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encrypt_key
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EncryptKey other = (EncryptKey) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.geteKey() == null ? other.geteKey() == null : this.geteKey().equals(other.geteKey()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encrypt_key
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((geteKey() == null) ? 0 : geteKey().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encrypt_key
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", eKey=").append(eKey);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}