package com.cloud.configservice.model;

import java.io.Serializable;

public class Env implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.config_server_name
     *
     * @mbg.generated
     */
    private String configServerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.context_path
     *
     * @mbg.generated
     */
    private String contextPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env.registry_address
     *
     * @mbg.generated
     */
    private String registryAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table env
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.id
     *
     * @return the value of env.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.id
     *
     * @param id the value for env.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.config_server_name
     *
     * @return the value of env.config_server_name
     *
     * @mbg.generated
     */
    public String getConfigServerName() {
        return configServerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.config_server_name
     *
     * @param configServerName the value for env.config_server_name
     *
     * @mbg.generated
     */
    public void setConfigServerName(String configServerName) {
        this.configServerName = configServerName == null ? null : configServerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.context_path
     *
     * @return the value of env.context_path
     *
     * @mbg.generated
     */
    public String getContextPath() {
        return contextPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.context_path
     *
     * @param contextPath the value for env.context_path
     *
     * @mbg.generated
     */
    public void setContextPath(String contextPath) {
        this.contextPath = contextPath == null ? null : contextPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.name
     *
     * @return the value of env.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.name
     *
     * @param name the value for env.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env.registry_address
     *
     * @return the value of env.registry_address
     *
     * @mbg.generated
     */
    public String getRegistryAddress() {
        return registryAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env.registry_address
     *
     * @param registryAddress the value for env.registry_address
     *
     * @mbg.generated
     */
    public void setRegistryAddress(String registryAddress) {
        this.registryAddress = registryAddress == null ? null : registryAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Env other = (Env) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getConfigServerName() == null ? other.getConfigServerName() == null : this.getConfigServerName().equals(other.getConfigServerName()))
            && (this.getContextPath() == null ? other.getContextPath() == null : this.getContextPath().equals(other.getContextPath()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getRegistryAddress() == null ? other.getRegistryAddress() == null : this.getRegistryAddress().equals(other.getRegistryAddress()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getConfigServerName() == null) ? 0 : getConfigServerName().hashCode());
        result = prime * result + ((getContextPath() == null) ? 0 : getContextPath().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getRegistryAddress() == null) ? 0 : getRegistryAddress().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", configServerName=").append(configServerName);
        sb.append(", contextPath=").append(contextPath);
        sb.append(", name=").append(name);
        sb.append(", registryAddress=").append(registryAddress);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}