package com.cloud.configservice.model;

import java.io.Serializable;

public class EnvParam implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env_param.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env_param.p_key
     *
     * @mbg.generated
     */
    private String pKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env_param.p_value
     *
     * @mbg.generated
     */
    private String pValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env_param.env_id
     *
     * @mbg.generated
     */
    private Long envId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table env_param
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env_param.id
     *
     * @return the value of env_param.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env_param.id
     *
     * @param id the value for env_param.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env_param.p_key
     *
     * @return the value of env_param.p_key
     *
     * @mbg.generated
     */
    public String getpKey() {
        return pKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env_param.p_key
     *
     * @param pKey the value for env_param.p_key
     *
     * @mbg.generated
     */
    public void setpKey(String pKey) {
        this.pKey = pKey == null ? null : pKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env_param.p_value
     *
     * @return the value of env_param.p_value
     *
     * @mbg.generated
     */
    public String getpValue() {
        return pValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env_param.p_value
     *
     * @param pValue the value for env_param.p_value
     *
     * @mbg.generated
     */
    public void setpValue(String pValue) {
        this.pValue = pValue == null ? null : pValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env_param.env_id
     *
     * @return the value of env_param.env_id
     *
     * @mbg.generated
     */
    public Long getEnvId() {
        return envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env_param.env_id
     *
     * @param envId the value for env_param.env_id
     *
     * @mbg.generated
     */
    public void setEnvId(Long envId) {
        this.envId = envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_param
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EnvParam other = (EnvParam) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getpKey() == null ? other.getpKey() == null : this.getpKey().equals(other.getpKey()))
            && (this.getpValue() == null ? other.getpValue() == null : this.getpValue().equals(other.getpValue()))
            && (this.getEnvId() == null ? other.getEnvId() == null : this.getEnvId().equals(other.getEnvId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_param
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getpKey() == null) ? 0 : getpKey().hashCode());
        result = prime * result + ((getpValue() == null) ? 0 : getpValue().hashCode());
        result = prime * result + ((getEnvId() == null) ? 0 : getEnvId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_param
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pKey=").append(pKey);
        sb.append(", pValue=").append(pValue);
        sb.append(", envId=").append(envId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}