package com.cloud.configservice.model;

import java.io.Serializable;

public class Property implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.p_key
     *
     * @mbg.generated
     */
    private String pKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.p_value
     *
     * @mbg.generated
     */
    private String pValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.env_id
     *
     * @mbg.generated
     */
    private Long envId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.label_id
     *
     * @mbg.generated
     */
    private Long labelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.project_id
     *
     * @mbg.generated
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table property
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.id
     *
     * @return the value of property.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.id
     *
     * @param id the value for property.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.p_key
     *
     * @return the value of property.p_key
     *
     * @mbg.generated
     */
    public String getpKey() {
        return pKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.p_key
     *
     * @param pKey the value for property.p_key
     *
     * @mbg.generated
     */
    public void setpKey(String pKey) {
        this.pKey = pKey == null ? null : pKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.p_value
     *
     * @return the value of property.p_value
     *
     * @mbg.generated
     */
    public String getpValue() {
        return pValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.p_value
     *
     * @param pValue the value for property.p_value
     *
     * @mbg.generated
     */
    public void setpValue(String pValue) {
        this.pValue = pValue == null ? null : pValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.env_id
     *
     * @return the value of property.env_id
     *
     * @mbg.generated
     */
    public Long getEnvId() {
        return envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.env_id
     *
     * @param envId the value for property.env_id
     *
     * @mbg.generated
     */
    public void setEnvId(Long envId) {
        this.envId = envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.label_id
     *
     * @return the value of property.label_id
     *
     * @mbg.generated
     */
    public Long getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.label_id
     *
     * @param labelId the value for property.label_id
     *
     * @mbg.generated
     */
    public void setLabelId(Long labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.project_id
     *
     * @return the value of property.project_id
     *
     * @mbg.generated
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.project_id
     *
     * @param projectId the value for property.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Property other = (Property) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getpKey() == null ? other.getpKey() == null : this.getpKey().equals(other.getpKey()))
            && (this.getpValue() == null ? other.getpValue() == null : this.getpValue().equals(other.getpValue()))
            && (this.getEnvId() == null ? other.getEnvId() == null : this.getEnvId().equals(other.getEnvId()))
            && (this.getLabelId() == null ? other.getLabelId() == null : this.getLabelId().equals(other.getLabelId()))
            && (this.getProjectId() == null ? other.getProjectId() == null : this.getProjectId().equals(other.getProjectId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getpKey() == null) ? 0 : getpKey().hashCode());
        result = prime * result + ((getpValue() == null) ? 0 : getpValue().hashCode());
        result = prime * result + ((getEnvId() == null) ? 0 : getEnvId().hashCode());
        result = prime * result + ((getLabelId() == null) ? 0 : getLabelId().hashCode());
        result = prime * result + ((getProjectId() == null) ? 0 : getProjectId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pKey=").append(pKey);
        sb.append(", pValue=").append(pValue);
        sb.append(", envId=").append(envId);
        sb.append(", labelId=").append(labelId);
        sb.append(", projectId=").append(projectId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}