package com.cloud.configservice.dao;


import com.cloud.configservice.model.EncryptKey;
import com.cloud.configservice.model.EncryptKeyExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface EncryptKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encrypt_key
     *
     * @mbg.generated
     */
    long countByExample(EncryptKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encrypt_key
     *
     * @mbg.generated
     */
    int deleteByExample(EncryptKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encrypt_key
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encrypt_key
     *
     * @mbg.generated
     */
    int insert(EncryptKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encrypt_key
     *
     * @mbg.generated
     */
    int insertSelective(EncryptKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encrypt_key
     *
     * @mbg.generated
     */
    List<EncryptKey> selectByExample(EncryptKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encrypt_key
     *
     * @mbg.generated
     */
    EncryptKey selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encrypt_key
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EncryptKey record, @Param("example") EncryptKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encrypt_key
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EncryptKey record, @Param("example") EncryptKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encrypt_key
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EncryptKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encrypt_key
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EncryptKey record);
}