package com.cloud.configservice.dao;

import com.cloud.configservice.model.EnvParam;
import com.cloud.configservice.model.EnvParamExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

@Mapper
public interface EnvParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_param
     *
     * @mbg.generated
     */
    long countByExample(EnvParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_param
     *
     * @mbg.generated
     */
    int deleteByExample(EnvParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_param
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_param
     *
     * @mbg.generated
     */
    int insert(EnvParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_param
     *
     * @mbg.generated
     */
    int insertSelective(EnvParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_param
     *
     * @mbg.generated
     */
    List<EnvParam> selectByExample(EnvParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_param
     *
     * @mbg.generated
     */
    EnvParam selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_param
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EnvParam record, @Param("example") EnvParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_param
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EnvParam record, @Param("example") EnvParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_param
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EnvParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table env_param
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EnvParam record);


    @Select("select id,p_key,p_value,env_id from env_param where env_id=#{id}")
    @Results({
            @Result(column = "id", property = "id", id=true),
            @Result(column = "p_key", property = "pKey", id=true),
            @Result(column = "p_value", property = "pValue", id=true),
            @Result(column = "env_id", property = "envId", id=true),
    })
    List<EnvParam> findEnvParamByEnvId(@Param("id") Long id);
}