package com.cloud.configservice.dao;

import com.cloud.configservice.dto.ProjectDTO;
import com.cloud.configservice.model.Project;
import com.cloud.configservice.model.ProjectExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

@Mapper
public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated
     */
    long countByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated
     */
    int deleteByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated
     */
    int insertSelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated
     */
    List<Project> selectByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated
     */
    Project selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Project record, @Param("example") ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Project record, @Param("example") ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Project record);

    @Select("SELECT project.id,project.name FROM project INNER JOIN project_envs ON project.id = project_envs.projects_id INNER JOIN env ON env.id = project_envs.envs_id WHERE env.id = #{id}")
    List<Project> findProjectByEnvId(@Param("id") Long id);

    @Select("select project.id,project.name from project where name=#{name}")
    Project selectProjectByName(@Param("name") String name);

    @Select("select * from project")
    @Results(value = {
            @Result(property = "id", column = "id", id = true),
            @Result(property = "name", column = "name"),
            @Result(property = "envs", column = "id", many = @Many(select = "com.doalso.config.dao.EnvMapper.selectEnvByProjectId")),
            @Result(property = "labels", column = "id", many = @Many(select = "com.doalso.config.dao.LabelMapper.selectLabelByProjectId")),
    })
    List<ProjectDTO> selectAllProject();

    @Select("select * from project where id=#{id}")
    @Results(value = {
            @Result(property = "id", column = "id", id = true),
            @Result(property = "name", column = "name"),
            @Result(property = "envs", column = "id", many = @Many(select = "com.doalso.config.dao.EnvMapper.selectEnvByProjectId")),
            @Result(property = "labels", column = "id", many = @Many(select = "com.doalso.config.dao.LabelMapper.selectLabelByProjectId")),
    })
    ProjectDTO selectProjectById(@Param("id") Long id);

}