package com.cloud.configservice.dao;

import com.cloud.configservice.model.Property;
import com.cloud.configservice.model.PropertyExample;
import org.apache.ibatis.annotations.*;


import java.util.List;

@Mapper
public interface PropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated
     */
    long countByExample(PropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated
     */
    int deleteByExample(PropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated
     */
    int insert(Property record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated
     */
    int insertSelective(Property record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated
     */
    List<Property> selectByExample(PropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated
     */
    Property selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Property record, @Param("example") PropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Property record, @Param("example") PropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Property record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Property record);

    @Select("SELECT property.* FROM property, project, env, label WHERE property.project_id = project.id AND property.env_id = env.id AND property.label_id = label.id AND project.NAME=#{application} AND env.NAME=#{profile} AND label.NAME=#{label}")
    @Results({
            @Result(column = "id", property = "id"),
            @Result(column = "p_key", property = "pKey"),
            @Result(column = "p_value", property = "pValue"),
            @Result(column = "env_id", property = "envId"),
            @Result(column = "label_id", property = "labelId"),
            @Result(column = "project_id", property = "projectId"),
    })
    List<Property> selectPropertyByNames(@Param("application") String application, @Param("profile") String profile, @Param("label") String label);


    @Delete("DELETE FROM property WHERE env_id=(SELECT id FROM env WHERE name=#{profile}) AND project_id=(SELECT id FROM project WHERE name=#{application}) AND label_id=(SELECT id FROM label WHERE project_id= (SELECT id FROM project WHERE name=#{application}))")
    Integer deletePropertyByNames(@Param("application") String application, @Param("profile") String profile, @Param("label") String label);
}